name: Just testing how to use env variables

on:
  push:
    branches:
      - feature/environment-usage
  workflow_dispatch:

jobs:
  fun_with_variables:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://mypage.com
      SUBPAGE: page_that_doesnt_exist
      FULL_LINK: $BASE_URL/$SUBPAGE

    steps:
      - name: print variables
        run: >-
          echo $BASE_URL &&
          echo $SUBPAGE &&
          echo $FULL_LINK
          
  widows_path:
    runs-on: windows-latest
    steps:
      - name: path
        run: |
          Get-ChildItem -Path 'C:\'
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: json_file
          path: C:\*.json
      - name: echo PROJECT_PATH
        run: |
          Write-Host ${{ env.PROJECT_ROOT }}
          
      - name: Set GITHUB_OUTPUT
        id: gh-output
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get GITHUB_OUTPUT
        run: echo "The value of SELECTED_COLOR ${{ steps.gh-output.outputs.SELECTED_COLOR }}"
      
      - name: tests
        run: echo "test msg" >> c:\test.txt
      - name: Set GITHUB_ENV
        run: |
          echo "NEW_VAR=$(Get-Content c:\test.txt)" >> ${env.GITHUB_ENV}
          echo ${{ env.NEW_VAR }}

  gha_vars:
    runs-on: windows-latest
    steps:
      - name: commit message
        run: |
          echo "${{ github.event.head_commit.message }}"
        
