name: Get Modified Files

on:
  push:
  pull_request:

jobs:
  get-modified-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: get changed files
        id: diff-files
        run: |
          echo "files=$(git diff --name-only HEAD~ HEAD)" >> "$GITHUB_OUTPUT"
      - name: echo output
        run: |
          echo ${{ steps.diff-files.outputs.files }}
