name: Get Modified Files

on:
  push:

jobs:
  get-modified-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        run: |
          git diff --name-only
