name: Get Modified Files

on:
  push:
  pull_request:

jobs:
  get-modified-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: get changed files
        id: diff-files
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "files<<$EOF" >> $GITHUB_OUTPUT
          echo "$(git diff --name-only HEAD~ HEAD)" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          
      - name: echo output
        run: |
          echo ${{ steps.diff-files.outputs.files }}
